spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    # 分布式配置中心服务端配置
    config:
      label: master
      server:
        git:
          uri: https://github.com/LinWenLiGit/Config.git
          search-paths: respo
          username:
          password:

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
